import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const Faq = () => {
  const faqs = [
    {
      question: 'What is Prospera?',
      answer:
        'Prospera is a platform based in Kuwait that allows you to invest in shares of properties and earn monthly dividends from rental income.',
    },
    {
      question: 'How does Prospera work?',
      answer:
        'Prospera lets you invest in fractional shares of properties. You can browse available properties, invest in shares, and receive monthly dividends from the rental income generated by these properties.',
    },
    {
      question: 'What are the benefits of investing with Prospera?',
      answer:
        'Investing with Prospera allows you to diversify your investment portfolio, earn passive income through monthly dividends, and invest in real estate without the need for large capital.',
    },
    {
      question: 'Is Prospera available to international investors?',
      answer:
        'Currently, Prospera is focused on the Kuwaiti market. Please check our website for updates on availability in other regions.',
    },
    {
      question: 'How do I get started with Prospera?',
      answer:
        'To get started with Prospera, sign up on our platform, browse available properties, and start investing in shares of properties that interest you.',
    },
    {
      question: 'What types of properties can I invest in?',
      answer:
        'With Prospera, you can invest in a variety of properties including residential, commercial, and mixed-use properties.',
    },
    {
      question: 'How is the rental income distributed?',
      answer: 'Rental income is distributed monthly to investors based on the number of shares they own in a property.',
    },
    {
      question: 'What is the minimum investment amount?',
      answer:
        'The minimum investment amount varies by property. Please check the details of each property listing for specific information.',
    },
    {
      question: 'Are there any fees associated with investing?',
      answer:
        'Prospera charges a small management fee for handling the properties and distributing rental income. Please refer to our fee schedule for detailed information.',
    },
    {
      question: 'How can I track my investments?',
      answer:
        'You can track your investments through your Prospera account dashboard, where you will find detailed information about your portfolio and earnings.',
    },
  ];

  return (
    <section className='w-full py-20 md:pb-32'>
      <div className='container'>
        <div className='flex w-full flex-col gap-16 overflow-hidden rounded-lg border border-border bg-card p-8 md:rounded-2xl lg:items-center lg:p-16'>
          <h1 className='mb-4 text-3xl font-semibold md:mb-11 md:text-5xl'>Frequently asked questions</h1>
          <div className='w-full'>
            <Accordion type='single' collapsible>
              {faqs.map((faq, index) => (
                <AccordionItem value={`item-${index}`} key={index}>
                  <AccordionTrigger className='text-lg hover:text-foreground/60 hover:no-underline'>
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent>{faq.answer}</AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Faq;
